### ISSUE TITLE
implement profile-1.0 secret transformation

### ISSUE THREAD

**Issue by devvythelopper** [abustany/lcp-decrypt#3]
Apparently there are two possible types of transformations applied to the -userKey as specified in the .lcpl. the "basic secret transformation" which does nothing to the user's passphrase (i.e. this is the one that is implemented in lcp-decrypt), and then there is a secret transformation that is derived from a master key in the following way using python code from an old version of DeDRM which was forcefully removed from github.

One can use that very python code and apply it to a passphrase and then give the result to lcp-decrypt as -userKey to successfully decrypt an epub which uses the profile-1.0 key transformation.

In the .lcpl file this type of key transformation is specified in the following fragment:

```
"encryption": {
    "profile": "http://readium.org/lcp/profile-1.0",
    "content_key": {
```

**Comment by devvythelopper** [comment]
nvm, it just ran without decrypting

**Comment by devvythelopper** [comment]
actually this works, but encryption.xml also specifies compression, and so I found a bug: lcp-decrypt does not decompress compressed files. so this works for uncompressed content files, but not for compressed ones.

**Comment by devvythelopper** [comment]
made an issue for the compression, including a "reference implementation" here: https://github.com/abustany/lcp-decrypt/issues/4

**Comment by abustany** [comment]
oh wow this is an interesting scheme :thinking: what is `input_hash` here, the SHA-256 of the clear text user key?

**Comment by devvythelopper** [comment]
frankly I'm not sure. I tried that very input_hash for the ebook I have with Thorium as a text user key to no avail.

reading through the DeDRM code where above excerpt is from, it seems (on first glance) that it is treated as a SHA-256 of a clear text user key. Or rather, DeDRM checks which algo is specified in the XML but implements only SHA-256. However that DeDRM could not decrypt the ebook I was trying to decrypt. 
Rather for this specific ebook I took the input_hash I had extract from the reading app, and applied this function to it, and then used the result with lcp-decrypt. 
I would go with the tryal and error route in lcp-decrypt: hash the key (according to the algo specified in the xml), and see if it matches the key_check from the xml. if not apply the function and hash (sha-256) the result and see if it matches. Or something like that. So that the user can give a text key or a hash to lcp-decrypt and it just tries and sees at which step in the transformation the input needs to be thrown in to get at the key.

**Comment by abustany** [comment]
what's not clear to me is, do we have examples of epubs that *currently* fail to decrypt with lcp-decrypt (ie after I pushed the fixes for incorrect path decoding etc)? If yes, I'm happy to take a look, but else it's all quite theoretical to me :)

**Comment by devvythelopper** [comment]
> I pushed fixes for couple of other issues, so maybe just give the latest version a try too, with a bit of luck your issues might be fixed :)

decrypting my ebook with the manually transformed key works with the current version, great!

>  I don't have any files that'd use the "weird" scheme, so I can't really test any changes I make. If you have any, could you forward them to me?

as @ienev pointed out, it might be sensible to not implement that transformation after all. Instead you might want to add the ability to load plugins, and then a plugin could implement a hook that transforms the userkey. But I don't know if that makes much of a difference, since one can also simply create a .py file and run the transformation.

**Comment by abustany** [comment]
> decrypting my ebook with the manually transformed key works with the current version, great!

:partying_face: 

> But I don't know if that makes much of a difference, since one can also simply create a .py file and run the transformation.

Agree, I don't want to deal with DMCA takedowns :sweat_smile: Though it'd actually be interesting to know if DeDRM got taken down precisely because of that LCP "master" key, or if this was just collateral damage. But if the key doesn't appear in the LCP standard, it's probably (supposed to be) secret :shrug: 

Feel free to close the ticket if you think it makes sense :)

**Comment by devvythelopper** [comment]
> > decrypting my ebook with the manually transformed key works with the current version, great!
> 
> 🥳
> 
> > But I don't know if that makes much of a difference, since one can also simply create a .py file and run the transformation.
> 
> Agree, I don't want to deal with DMCA takedowns 😅 Though it'd actually be interesting to know if DeDRM got taken down precisely because of that LCP "master" key, or if this was just collateral damage. But if the key doesn't appear in the LCP standard, it's probably (supposed to be) secret 🤷

I would assume this to be exactly the reason. For as far as I understand it, taking down content that is DMCA protected means that this content is not in the public domain. And the only thing in DeDRMs code that was not given to the public domain is the master key. But then again, corporations and institutions are even able to patent algorithms (such as mp3), so maybe the whole transformation algorithm is protected despite how simple it is.

> 
> Feel free to close the ticket if you think it makes sense :)

👍

**Comment by ienev** [comment]
> do we have examples of epubs that currently fail to decrypt with lcp-decrypt (ie after I pushed the fixes for incorrect path decoding etc)
I have a profile 2.0 one that can't be decrypted, neither by lcp-decrypt nor by DeDRM (the version that worked with profile 1.0)
